name:                spinsel
github:              "svkampen/spinsel"
license:             MIT
author:              "Sam van Kampen"
maintainer:          "sam@tehsvk.net"
copyright:           "2023 Sam van Kampen"
language:            GHC2021

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/svkampen/spinsel#readme>

dependencies:
- base >= 4.7 && < 5
- time >= 1.10
- megaparsec >= 9.2.0
- unix >= 2.7
- split >= 0.2
- filepath >= 1.4
- text >= 1.2
- lucid >= 2.10
- mustache >= 2.4
- mtl >= 2.2
- unordered-containers >= 0.2
- string-interpolate >= 0.3.2
- directory >= 1.3
- cmark >= 0.6
- process >= 1.6
- mmorph >= 1.2.0
- skylighting >= 0.13
- blaze-markup >= 0.8.2
- syb >= 0.7.2
- bytestring >= 0.11.0
- file-embed >= 0.0.14
- data-default >= 0.7.1
- optparse-applicative >= 0.17.1
- template-haskell >= 2.18
- vector >= 0.10
- htoml-megaparsec >= 2.0
- regex-base >= 0.94
- regex-tdfa >= 1.3
- feed >= 1.3
- xml-types >= 0.3
- ginger >= 0.10.5


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  spinsel-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spinsel
    when:
    - condition: false
      other-modules: Paths_spinsel

tests:
  spinsel-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spinsel
